services:
  stathandler:
    build: .
    container_name: stathandler
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./data:/data
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8001"]
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}